[Variables]
; ---------------------------------------------
; TYPOGRAPHY STYLES
; ---------------------------------------------
TextHeaderFont=Segoe UI Light
TextHeaderSize=34

TextSubheaderFont=Segoe UI Light
TextSubheaderSize=26

TextSemilightFont=Segoe UI Semilight
TextSemilightSize=18

TextSubtitleFont=Segoe UI Regular
TextSubtitleSize=14.5

TextBaseFont=Segoe UI Semibold
TextBaseSize=10.5

TextBodyFont=Segoe UI Regular
TextBodySize=10.5

TextCaptionFont=Segoe UI Regular
TextCaptionSize=9

; ---------------------------------------------
; THEME STYLES
; ---------------------------------------------
CurrentThemeBackground=0,0,0,128
CurrentThemeTextColour=255,255,255,255
CurrentThemeGreyAccent=69,69,69,255